[package]
name = "crytagraph"
version = "0.1.0"
authors = ["Philip Vejre <philipvejre@gmail.com>"]

[dependencies]
time = "*"
rand = "*"
structopt = "*"
structopt-derive = "*"
num_cpus = "*"
crossbeam-utils = "*"
lazy_static = "*"
fnv = "*"
indexmap = "*"
smallvec = "*"
itertools = "*"

[[bin]]
name = "generate"
path = "src/bin_generate.rs"

[[bin]]
name = "enumerate"
path = "src/bin_enumerate.rs"