[package]
name = "mask_generator"
version = "0.1.0"
authors = ["psve <psve@dtu.dk>"]

[dependencies]
time = "*"
structopt = "*"
structopt-derive = "*"
bloom_filter = { path = "../bloom_filter" }

[[bin]]
name = "generate"
path = "src/bin_generate.rs"
